nome = str( input ('Digite seu nome completo:')).strip()
print(nome.upper())
print(nome.lower())
#letras = len(nome.replace(' ', ''))
#print(f'Seu nome tem {letras} letras')
print(f'Seu nome tem {len(nome)-nome.count(' ')} letras')
dividido = nome.split()
primeiro = len(dividido[0])
print(f'Seu primeiro nome tem {primeiro} letras')